// 起源岛内容 —— 全部取自 datawhalechina/easy-vibe main 分支 docs/zh-cn/stage-1/<slug>/index.md
// 提炼笔记见 scratch/easy-vibe-stage1-notes.md(每章含抓取 URL),忠于原文,未杜撰。
import type { IslandDef } from './types'

export const ORIGIN_ISLAND: IslandDef = {
  id: 'origin',
  name: '起源岛',
  region: 'stage-1',
  lockedByDefault: false,
  nextIslandId: 'sea2-island1',
  nodes: [
    {
      id: 'origin-1', title: '学习地图', chapterSlug: 'learning-map', kind: 'main', order: 1,
      coins: 10, position: { x: 14, y: 78 },
      learn: [
        { title: '什么是 Vibe Coding?',
          body: 'Vibe Coding 就是"用说话来编程"。你不用自己一行行敲代码,而是把想做的东西用大白话告诉 AI,让它来写。以前做软件门槛很高,要懂编程、懂算法;现在大语言模型把这件事变成了人人能上手的工具。以前最难的是"怎么写代码",现在最难的是"你到底要做什么"——想清楚需求,比记住语法重要得多。' },
        { title: '两周做出能演示的原型',
          body: '这门课不挑出身:学生、运营、老师、医生都能学。第一阶段的目标很实在——用 AI 编程工具独立做出一个网页应用,把想法变成能点击的原型,再加上文生图、智能对话这类 AI 功能,遇到报错也知道怎么让 AI 帮你修。一句话:做出一个"能跑、能给别人演示"的东西,而不是停留在想法。' },
        { title: '为什么要项目制"模拟社会毒打"',
          body: '真实工作里,老板常常只丢给你一句话:"做个 xxx,达到 yyy 效果"。没有文档、没有现成框架、没有标准答案。这门课故意用有点难度的项目逼你练三件事:拆解问题、自己找资料、从创意到上线走完整闭环。短期折磨,长期让你"更能扛事"。' },
        { title: '会提问 = 会用 AI',
          body: '同一个报错,会问的人几句话拿到能落地的修法,不会问的人只能收到泛泛而谈。诀窍是补齐上下文:报错日志、代码、配置用复制粘贴(要完整);界面问题用截图(截全屏+标重点)。注意截图沟通需要 AI 支持图片输入(多模态)。想"学会"而不只是要答案,可以让 AI 先用 5 句话讲清概念,再出题反问你。' },
      ],
      task: {
        type: 'quiz',
        question: '按照 easy-vibe 学习地图的说法,"Vibe Coding"指的是什么?',
        options: [
          '用更快的打字速度写代码',
          '主要靠和 AI 对话(说出需求)来完成编程项目,而不是自己直接写代码',
          '背熟一门编程语言的全部语法',
          '只能用来做小游戏的玩具编程方式',
        ],
        answerIndex: 1,
        explain: '原文定义 Vibe Coding 是"用说话来编程"——依赖与 AI 对话而非直接写代码的方式完成项目。它不是打字技巧,不需要死记语法,课程目标恰恰是做出真实可用的产品原型而非玩具。',
      },
    },
    {
      id: 'origin-2', title: '找到好点子', chapterSlug: 'finding-great-idea', kind: 'main', order: 2,
      coins: 10, position: { x: 32, y: 60 },
      learn: [
        { title: '小明的 20 万学费:方向错了,越努力越错',
          body: '程序员小明花一年业余时间做了个功能齐全的健身 APP,结果用户用一次就卸载,亏了 20 万。他输在起点:从没问过"用户为什么需要另一个健身 APP"。Keep 已经够好,用户凭什么换?做之前问三个问题——用户愿意付费吗?愿意改变习惯吗?不解决会有大损失吗?三个都答不上来,就别开工。' },
        { title: '痛点、爽点、痒点:先治痛',
          body: '需求分三层:痛点是"止痛药"(不解决很难受),用户不得不买单;爽点是即时满足(外卖 30 分钟送达),能留住人但单独很难收费;痒点是"维生素"(记录喝水、照片加滤镜),可有可无最容易被砍。优先级永远是痛点>爽点>痒点。最常见的错误是把痒点包装成痛点去卖——用户不会买账。' },
        { title: '横切人群、纵挖场景',
          body: '"做个健身 APP"太泛,通用市场早被大平台占了。正确做法:横向切分——把"想健身的人"切成增肌党、糖尿病患者、产后妈妈……挑痛点最痛、付费意愿最强、你最理解的人群。再纵向深挖——描述这个人完整的一天,找到恐惧、焦虑、孤独这些情绪触点。解决情绪,才有人付费。' },
        { title: '用 AI 把点子磨成计划',
          body: '把想法丢给 AI 多轮对话:先说出原始想法和担忧;让它规划 MVP(最小可行产品);把顾虑一个个抛出去要方案;最后整理成行动计划+验证指标。预售测试付费意愿:付定金比例>10% 说明需求真实,5-10% 需打磨,<5% 不成立。记住口诀:一人一事一切入,横切纵挖找痛点,AI 对话磨概念,五步验证再动手。' },
      ],
      task: {
        type: 'prompt-forge',
        brief: '把「帮我做一个健身 APP」这句空话,锻造成 AI 能落地的好提示词',
        basePrompt: '帮我做一个健身 APP。',
        forgeRounds: [
          { options: [
            { text: '横切人群:锁定最痛的细分人群', effective: true,
              why: '原文:不要服务"所有人",找到"最痛的那个人群",越细分付费意愿越强。',
              fragment: '目标用户:产后妈妈(痛点真实、付费意愿强、竞争不激烈)。' },
            { text: '把功能列表写满 20 个', effective: false,
              why: '大而全正是小明亏 20 万的路线——先验证需求,再谈功能。', fragment: '' },
            { text: '强调界面要炫酷高级', effective: false,
              why: '用户买单的是"解决恐惧、消除焦虑",不是外观。', fragment: '' },
          ] },
          { options: [
            { text: '让 AI 夸夸这个点子', effective: false,
              why: '打磨点子不是寻找认可,要的是方案不是掌声。', fragment: '' },
            { text: '说出担忧,并要求规划 MVP', effective: true,
              why: '原文模板核心:「我想做一个[产品概念],但我担心[担忧]。请帮我:1.规划一个 MVP…」',
              fragment: '我担心内容制作和推广成本。请帮我:1. 规划一个 MVP;2. 给出技术实现建议;3. 估算成本。' },
            { text: '要求 AI 保证月入十万', effective: false,
              why: 'AI 替代不了市场验证,空头承诺毫无意义。', fragment: '' },
          ] },
          { options: [
            { text: '直接要求生成全部代码', effective: false,
              why: '方向没验证就写代码——方向错了,越深入错得越多。', fragment: '' },
            { text: '加一句「越快越好」', effective: false,
              why: '催促不会提高质量,补齐信息才会。', fragment: '' },
            { text: '设定验证指标', effective: true,
              why: '原文 5 步验证:预售付定金比例 >10% 真实可投入,5-10% 需打磨,<5% 不成立。',
              fragment: '4. 设定验证指标:第一个月 100 个用户,预售付定金比例 >10% 才追加投入。' },
          ] },
        ],
        rubric: ['说清产品概念与目标人群', '说出担忧/风险', '要求规划 MVP', '要求设定验证指标'],
        exampleGood: '我想做一个「产后妈妈恢复助手」,但我担心内容制作和推广成本。请帮我:1. 规划一个 MVP;2. 给出具体的技术实现建议;3. 估算成本;4. 设定验证指标(预售付定金比例 >10% 说明需求真实)。',
      },
    },
    {
      id: 'origin-3', title: 'AI IDE 入门', chapterSlug: 'introduction-to-ai-ide', kind: 'main', order: 3,
      coins: 10, position: { x: 22, y: 40 },
      learn: [
        { title: 'IDE 和 AI IDE:工具箱 vs 实习工程师',
          body: 'IDE 是程序员的工作台:写代码有高亮、补全,能一键运行调试。但普通 IDE 只是工具箱,报错要自己读、文件要自己建。AI IDE 多了一个能听懂人话的"实习工程师":说一句"做个登录页"它就生成代码,丢个报错它就分析原因,确认后还能自动建文件、装环境、批量改代码。市面上大多数 AI IDE(Trae、Cursor 等)都基于 VS Code,会用一个就会用全部。' },
        { title: '先能跑,再变好看',
          body: '新手最大的坑是一上来就要"像淘宝那样的网站",结果拿到一大团跑不起来的代码。正确节奏分三步:第一步只要一个最小例子(浏览器里能看到一行字就行);第二步在能跑的基础上一块块加内容,每加一步运行确认一次;第三步结构稳了再谈美化。这样哪步出问题都能退回上一个正常版本。' },
        { title: 'AI 停住了?它在等你',
          body: 'Agent 干活时经常"不动了",多数不是卡死,而是在等你:等你回车确认、等你点 Run,或者它启动了本地服务(看到 localhost:3000 这类网址)需要你点 Skip 跳过。改坏了别慌,所有 AI IDE 都支持回退(Revert)。反复修不好就换个模型再试——不同模型擅长的事不一样。' },
        { title: '把画面扔给 AI,但先确认它"看得见"',
          body: '说不清问题就别硬挤术语:报错红字全选复制发过去,界面不对就截图。但注意:纯文本大模型看不懂图片,只有多模态模型才能"看图"。比如 Trae 里 Kimi、Gemini、GPT 系列支持图片输入,而 GLM、DeepSeek-V3.1、Qwen-3-Coder 不支持。模型不支持图,就改成复制粘贴文字描述。' },
      ],
      task: {
        type: 'match',
        pairs: [
          { left: '端口 (Port)', right: '同一栋大楼里每个房间的门牌号' },
          { left: 'localhost', right: '"这台电脑自己"' },
          { left: '前端', right: '用户看得见、点得到的"店面和店员"' },
          { left: '后端', right: '服务器上看不见的"仓库和账本系统"' },
        ],
      },
    },
    {
      id: 'origin-4', title: '搭建原型', chapterSlug: 'building-prototype', kind: 'main', order: 4,
      coins: 10, position: { x: 44, y: 28 },
      learn: [
        { title: '别急着写代码:先问业务',
          body: '老板说"让上新效率高一点",这句话不能直接变成提示词。你不是用户,AI 也不懂你的业务,瞎猜做出来的东西"看着像那么回事,实际根本用不了"。正确做法是先去问一线运营:"你每天在做什么?哪里最麻烦?"先搞懂业务,再动手——代码只是工具,找准问题才是第一步。' },
        { title: '收敛:从一堆问题挑最痛的一个',
          body: '用户会告诉你一堆烦恼:节奏乱、店太多、做图慢……全都想解决,最后只会做出"大而全但不好用"的东西。要学会收敛:把问题分类,挑最痛、最急、最能解决的那个先做。本章最终只做两个功能——批量生成商品图文草稿+把好用的方案存成模板。做一两个功能但真帮到用户,胜过做十个功能没人用。' },
        { title: '提示词从大白话开始',
          body: '新手不用追求完美提示词。先用自己的话把想法说出来(哪怕很粗糙),然后让 AI 帮你扩写成清晰的业务文档,再生成适合发给 AI IDE 的提示词。AI 扩写时会反问"要不要支持批量上传?"这类你没想到的问题,等于帮你做了一轮需求检查。' },
        { title: '用测试数据快速走通全流程',
          body: '原型做完不等于能用。让 AI 在界面上加"测试数据入口",一键填充就能从头走一遍用户流程;让 AI 模拟真实生成过程(点击后等一会儿才出结果);最后让 AI 对照最初需求输出功能清单 checklist——哪些完成了、哪些没实现,照着清单补。' },
      ],
      task: {
        type: 'proto-builder',
        brief: '电商运营的两大真痛点:「批量做图做文案太费劲」「好方案存不下来」。拼出最小可用的素材工作台原型——只放核心功能,别堆没人要的!',
        slots: [
          { id: 'top', label: '顶栏', accepts: ['title'] },
          { id: 'input', label: '输入区', accepts: ['product-form', 'image-upload'] },
          { id: 'action', label: '操作区', accepts: ['batch-generate'] },
          { id: 'result', label: '结果区', accepts: ['draft-list'] },
          { id: 'side', label: '侧栏', accepts: ['template-lib'] },
        ],
        blocks: [
          { id: 'title', label: '标题栏', emoji: '🏷️' },
          { id: 'product-form', label: '商品信息表单', emoji: '📋' },
          { id: 'image-upload', label: '图片上传', emoji: '📤' },
          { id: 'batch-generate', label: '批量生成按钮', emoji: '⚡' },
          { id: 'draft-list', label: '图文草稿列表', emoji: '🗂️' },
          { id: 'template-lib', label: '模板库', emoji: '📚' },
          { id: 'vip-popup', label: '会员充值弹窗', emoji: '💰', distractor: true },
          { id: '3d-hall', label: '3D 商品展厅', emoji: '🕶️', distractor: true },
          { id: 'points-mall', label: '积分商城', emoji: '🎯', distractor: true },
        ],
      },
    },
    {
      id: 'origin-5', title: '集成 AI 能力', chapterSlug: 'integrating-ai-capabilities', kind: 'main', order: 5,
      coins: 10, position: { x: 64, y: 42 },
      learn: [
        { title: 'API 三件套:地址、钥匙、参数',
          body: 'API 就是"按约定格式发问题、按约定格式收答案"。读任何 API 文档只盯三样东西:服务地址(endpoint,比如 /v1/chat/completions 管文本生成)、身份凭证(API Key,一串 sk- 开头的密码)、调用参数怎么填。把这三点弄清楚,调通只是时间问题,剩下的体力活交给 AI IDE 和 SDK。' },
        { title: '接入任何 AI 能力的万能三步',
          body: '不管是文字、图生文还是文生图,流程一模一样:①去官方平台注册并创建 API Key;②在官方文档里找到现成的调用示例;③把示例+Key 一起粘贴到 AI IDE,告诉它"帮我接到这个按钮上"。换模型也简单:大多数服务都是 OpenAI 兼容接口,只需改三处——基础 URL、API Key、模型名称。' },
        { title: 'LLM、VLM、文生图:各管一摊',
          body: '纯文本大模型(如 DeepSeek)只会处理文字,看不懂图片;想让 AI"看图说话"(上传商品图自动写卖点)要用视觉语言模型 VLM(如 Qwen3 VL);想让 AI"画图"(生成海报、主图)要用图像生成模型(如字节的 Seedream 即梦)。它们还能串联:先用 VLM 分析参考图,再把分析结果喂给文生图模型出新图。' },
        { title: 'API Key 是钱包钥匙,看好它',
          body: '别人拿到你的 API Key,就能替你调接口、花你的钱。三条铁律:不发群聊不截图上网;不硬编码进代码提交到 Git(尤其公开仓库);怀疑泄露立刻换新 Key。教程里直接把 Key 粘进 AI IDE 只是练习时的权宜之计,正规项目要把 Key 放进配置文件管理。' },
      ],
      task: {
        type: 'match',
        pairs: [
          { left: 'DeepSeek', right: '文本生成 LLM(让应用真正写出文案)' },
          { left: 'Qwen3 VL', right: '图像理解/看图说话(上传商品图生成卖点)' },
          { left: 'Seedream 即梦', right: '图像生成与编辑(文生图、做电商海报)' },
          { left: 'API Key', right: '"通行证+钱包钥匙"(泄露会被别人花钱)' },
        ],
      },
    },
    {
      id: 'origin-6', title: '完整项目实战', chapterSlug: 'complete-project-practice', kind: 'main', order: 6,
      coins: 10, position: { x: 82, y: 26 },
      learn: [
        { title: 'Happy Path 之外才是产品',
          body: '新手做原型只做"一切顺利"的路线:点击→成功→显示。但现实是 AI 要等几秒、API 会挂、网络会断。产品级原型要补三件事:点生成时按钮变"生成中..."加 Loading 动画;请求失败弹出红色提示"生成失败,请稍后重试"并允许重试;数据用 LocalStorage 存起来,刷新页面不丢。这些"隐形环节"才是 Demo 和产品的分界线。' },
        { title: 'Mock 数据:给原型注入灵魂',
          body: '演示时列表里只有"测试数据1、测试数据2"是打动不了人的。让 AI 帮你造一批逼真数据:先让它设计 JSON 数据结构,再像给实习生布置任务一样下要求——标题要"抖音风"带 Emoji、文案要口语化、图片用随机图服务保证每张不同。再配合 LocalStorage 做"假增删改",原型就像一个运营了半年的真产品。' },
        { title: '观察而非引导:让真人帮你找问题',
          body: '原型做好后拿给朋友同事试用,关键纪律是闭嘴观察:不要说"点这里",看他们自己会点哪里——找不到按钮就是设计有问题。AI 还没接好?用"绿野仙踪法":你人工在后台改数据假装是 AI 返回的,先验证用户到底需不需要这个功能。收到吐槽别慌:你负责发现问题,改代码交给 AI。' },
        { title: '毕业设计四条硬标准',
          body: 'Stage 1 大作业要做一个自选场景的 AI 产品原型,过关标准四条:①场景明确(选定具体行业);②逻辑闭环(核心流程跑通,不只 Happy Path);③AI 驱动(真实调用大模型 API,不是预设回复);④体验完整(有 Loading、错误处理、模拟数据)。交两样东西:能跑的原型应用+30 秒演示视频。' },
      ],
      task: {
        type: 'quiz',
        question: '本章提到的"Wizard of Oz(绿野仙踪法)"指的是什么做法?',
        options: [
          '给原型加上华丽的绿色主题动画效果',
          '让 AI 自动生成一批童话风格的测试数据',
          'AI 能力还没接好时,由人工在后台手动改数据来模拟 AI 返回,先验证用户是否需要这个功能',
          '把所有按钮藏起来,考验用户能不能找到',
        ],
        answerIndex: 2,
        explain: '原文在"收集反馈与快速迭代"一节定义:AI 还没接好时,可以人工在后台手动改数据模拟 AI 返回,目的是低成本先验证"用户是否需要这个功能"。',
      },
    },
    // ===== 隐藏宝箱(附录彩蛋) =====
    {
      id: 'origin-t1', title: '双钻模型', chapterSlug: 'appendix-double-diamond', kind: 'treasure', order: 0,
      coins: 5, position: { x: 8, y: 22 },
      learn: [
        { title: '两个钻石,四个动作',
          body: '双钻模型是英国 Design Council 推广的设计流程:第一个钻石管"做对的事情"——先 Discover(广泛调研用户和问题)再 Define(收敛出一个清晰的问题定义);第二个钻石管"把事情做对"——先 Develop(围绕这个问题发散多种方案)再 Deliver(挑一个做成可测试的最小版本去验证)。每个钻石都是"先发散、再收敛"。' },
        { title: '新手最大的坑:跳过第一个钻石',
          body: '刚有个点子就开画原型、写 PRD、接模型——这是最常见的失败方式。问题不是不认真,而是你根本没确认这个问题值不值得解决,结果"很努力地在错误方向上加速"。双钻的纪律是:发散之后必须进入判断和取舍,Define 完了也不许为了好做的方案偷偷改题。' },
        { title: 'AI 产品更需要双钻',
          body: '做 AI 产品特别容易"能力先行":满脑子都是要不要接多模态、做 Agent、加工作流。双钻逼你先回答:用户到底在哪个环节卡住了?这个卡点非 AI 不可吗?否则就会做出"能力很强、价值很弱"的东西。可以让 AI 当"阶段守门员",判断你在哪个阶段、是不是跳步了。' },
      ],
      task: {
        type: 'truefalse',
        statements: [
          { text: '双钻模型的第一个钻石(Discover+Define)解决的是"做对的事情",即先搞清楚要解决什么问题。', isTrue: true },
          { text: '按照双钻模型,Deliver 阶段必须把完整产品全部做完并正式上线才算完成。', isTrue: false },
          { text: '每个钻石都包含"发散"和"收敛"两个相反的动作。', isTrue: true },
          { text: '在 Develop 阶段,如果发现某个方案更容易实现,可以反过来修改问题定义去适配这个方案。', isTrue: false },
        ],
        explain: 'Deliver 的准确含义是"把方案变成可测试、可验证、可迭代的东西",低保真原型/MVP/小规模测试都算;Define 后为方案偷偷改题"很危险"——你可能是在为偏爱的方案找理由。',
      },
    },
    {
      id: 'origin-t2', title: 'Mom Test', chapterSlug: 'appendix-mom-test', kind: 'treasure', order: 0,
      coins: 5, position: { x: 58, y: 76 },
      learn: [
        { title: '你妈妈不会说你的点子烂',
          body: 'Mom Test 来自 Rob Fitzpatrick 的同名书。名字的含义:连你妈妈都很难当面说"这是个烂想法"——她不想伤害你,会下意识鼓励你。所以"挺好的""我会用"这类回答不是验证,是礼貌。问题不在对方撒谎,而在你把问题问成了任何人都会顺着你回答的样子。访谈的目标是收集证据,不是收集鼓励。' },
        { title: '三个原则:问过去,不问未来',
          body: '①少谈你的点子,多问对方过去的真实经历:"最近一次遇到这个问题是什么时候?当时怎么处理的?"②少要抽象意见,多挖具体事实:值钱的信息是"我上周为这事折腾了 2 小时""我上个月为类似工具花过钱"。③别问"你想要什么功能",去看他现在怎么凑合解决——现有替代方案才是你的真实竞争对手。' },
        { title: '"我会用"不等于验证通过',
          body: '人会高估未来的自己:"如果有我应该会用"几乎不可信。真正的验证要看用户是否愿意付出真实成本:花时间试用、忍受切换成本、甚至掏钱。另外三个坑:别把访谈开成产品介绍会;别只找熟人聊(熟人更爱鼓励你);聊完马上整理,否则信息很快变成模糊印象。' },
      ],
      task: {
        type: 'npc-dialog',
        npcName: '老妈',
        scenario: '你想做「产后妈妈恢复助手」,回家找老妈验证点子。按 Mom Test 的方法问出真情报!',
        goal: { validNeeded: 3, maxViolations: 3 },
        rounds: [
          { cards: [
            { question: '妈,你最近一次想恢复锻炼是什么时候?当时怎么做的?', valid: true,
              reply: '上个月吧,半夜搜了盆底肌修复的视频,跟着练了两天,不知道动作对不对,就放弃了。',
              lesson: '问过去的真实经历,挖到了具体行为——原文好问题:「最近一次遇到这个问题是什么时候?」' },
            { question: '我想做个产后妈妈恢复 APP,你觉得这个想法怎么样?', valid: false,
              reply: '挺好的呀,妈妈觉得你做什么都行!',
              lesson: '问意见只会收获鼓励——连你妈都很难当面说"这是个烂想法"。' },
            { question: '这个 APP 以后肯定比 Keep 好用,对吧?', valid: false,
              reply: '对对对,肯定比那个什么 Keep 好!',
              lesson: '把"正确答案"塞进问题里,对方只能顺着你说。' },
          ] },
          { cards: [
            { question: '你现在是怎么解决产后恢复这个问题的?', valid: true,
              reply: '就在妈妈群里问问,再不就刷刷小红书,东一榔头西一棒槌的。',
              lesson: '现有替代方案才是你的真实竞争对手——「看清现有替代方案,比直接问你想要什么更重要」。' },
            { question: '如果有这样一个 APP,你会用吗?', valid: false,
              reply: '会呀会呀,有的话我应该会用。',
              lesson: '人会高估未来的自己,"我会用"几乎不可信。' },
            { question: '你觉得 AI 动作纠正这个功能重要吗?', valid: false,
              reply: '听起来好高级,那应该挺重要的吧?',
              lesson: '抽象意见没有价值,要问具体事实。' },
          ] },
          { cards: [
            { question: '你为了产后恢复花过钱吗?花在哪了?', valid: true,
              reply: '报过一个产后修复班,两千多呢!去了三次实在没时间,就没再去了。',
              lesson: '已付出的真实成本是最硬的证据——原文:「你上次为了这个问题花过钱吗?」' },
            { question: '你愿意为这个功能付费吗?', valid: false,
              reply: '要是不贵的话……应该愿意吧?',
              lesson: '假设性付费承诺不可信,要看过去真实花过的钱。' },
            { question: '妈,你支持我创业吗?', valid: false,
              reply: '支持!妈永远支持你!',
              lesson: '原文:「不要把访谈做成你在寻找认可。」' },
          ] },
          { cards: [
            { question: '整个恢复过程里,最烦、最没底的是哪一步?', valid: true,
              reply: '最没底的是不知道自己练得对不对,也没人盯着,慢慢就不练了。',
              lesson: '问流程里最烦、最慢、最不放心的一步——痛感藏在细节里。' },
            { question: '我打算下个月辞职做这个,你说行不行?', valid: false,
              reply: '啊?那……你自己决定就好……',
              lesson: '这是在要承诺不是要事实,对方只会含糊安抚。' },
            { question: '你身边的妈妈们肯定也需要这个吧?', valid: false,
              reply: '应该都需要吧,大家都差不多。',
              lesson: '替别人猜需求+诱导式问法,双重问废。' },
          ] },
          { cards: [
            { question: '你之前试过哪些办法?后来为什么不用了?', valid: true,
              reply: '跟过直播课,时间凑不上;买过束腹带,戴着难受就闲置了。',
              lesson: '过去试过又放弃的方案里,藏着真实约束和不满。' },
            { question: '产品上线了你会推荐给姐妹们吗?', valid: false,
              reply: '会呀,到时候一定帮你宣传!',
              lesson: '未来的承诺是人情,不是验证。' },
            { question: '你觉得界面做成粉色还是绿色好?', valid: false,
              reply: '都好看,妈觉得都行。',
              lesson: '方向还没验证就追问外观/功能,为时过早。' },
          ] },
        ],
      },
    },
    {
      id: 'origin-t3', title: 'JTBD', chapterSlug: 'appendix-jobs-to-be-done', kind: 'treasure', order: 0,
      coins: 5, position: { x: 90, y: 62 },
      learn: [
        { title: '用户在"雇用"你的产品',
          body: 'JTBD(Jobs to Be Done)的核心:用户不是在买功能,而是在某个具体时刻"雇用"一个方案帮自己完成进展。买三明治的上班族雇的不是三明治,是"赶时间的早晨最省脑力地解决一顿饭"。看懂这一层,你的竞争对手就不再只是同类 App,而是用户现在所有的替代方案——包括 Excel、实习生和"干脆不做"。' },
        { title: '一句话公式:场景+想要+以便于+现状',
          body: '把模糊点子收敛成需求,套这个句式:「当______的时候,我想要______,以便于______。现在我只能通过______来勉强完成这件事。」写好这句话等于写清了五要素:场景、触发、想完成的进展、当前替代方案、成功标准。哪个空填不出来,说明方向还没想清楚。' },
        { title: '三层 job:功能、情绪、社会',
          body: '用户嘴上说的是功能层("我要总结、要改写"),但付费意愿往往在情绪层(不想慌、不想显得不专业、想有掌控感),黏性常常在社会层(在团队里显得更靠谱)。只做功能层的 AI 产品演示很炫但留不住人,因为功能最容易被替代。多问一层:用户用完之后,情绪上轻松了什么?在别人眼里变成了什么样?' },
      ],
      task: {
        type: 'quiz',
        question: '按照 JTBD 的观点,一个"AI 会议纪要工具"的真正竞争对手最可能是以下哪一项?',
        options: [
          '用户当前所有可接受的替代方案,比如自己回忆手工整理、让实习生记、甚至干脆不整理',
          '只有另一款长得很像的 AI 纪要 App',
          '和会议无关的游戏类 App',
          '没有竞争对手,因为 AI 功能是全新的',
        ],
        answerIndex: 0,
        explain: 'JTBD 认为用户是在"雇用"方案完成进展,原文明确说"谁是替代方案,谁就是你的真实竞争环境"——包括手工硬撑和拖着不做。',
      },
    },
    {
      id: 'origin-t4', title: '常见报错', chapterSlug: 'appendix-b-common-errors', kind: 'treasure', order: 0,
      coins: 5, position: { x: 86, y: 84 },
      learn: [
        { title: '报错三连:截图、问 AI、照做',
          body: 'AI 时代的调试不需要你看懂错误。标准动作就一句:看到报错→截图→问 AI→按它说的做。提问把三件事说清楚:刚才做了什么("我点了保存按钮")、现在看到什么("页面白屏了")、想要什么效果("我想让数据存上")。用大白话、按时间顺序说,最好描述+截图一起发。慌张瞎改、搜半小时引擎、独自 debug 到深夜,都是在浪费时间。' },
        { title: 'F12 不是第一步,是第二步',
          body: '遇到问题别急着打开开发者工具——先把现象和截图直接丢给 AI,很多时候它看一眼就给出方案。只有当 AI 说"需要更多信息"时才按 F12,按问题类型对症截图:页面白屏/报错→Console 标签截红色报错;数据存不上/接口出错→Network 标签重新操作一遍,截请求、参数、返回;样式不对→右键元素"检查"截 Styles 面板。' },
      ],
      task: {
        type: 'error-er',
        intro: '两位像素病人等待会诊。按本章方法论选对每一步诊断动作,误诊 3 次病情就恶化了!',
        cases: [
          {
            symptom: '病人A:点开页面一片白,什么都不显示',
            steps: [
              {
                prompt: '第一步先做什么?',
                options: [
                  { text: '描述现象 + 截图,直接丢给 AI', correct: true, feedback: '' },
                  { text: '立刻打开 F12 逐条分析错误', correct: false, feedback: '原文:不要急着打开 F12——先把现象和截图丢给 AI,很多时候它看一眼就给方案。' },
                  { text: '搜索引擎搜半小时「白屏怎么解决」', correct: false, feedback: '原文反面清单:花半小时搜索"xxx 错误怎么解决"是在浪费时间。' },
                ],
              },
              {
                prompt: 'AI 说「需要更多信息」。白屏/报错类问题,该按 F12 截哪个面板?',
                options: [
                  { text: 'Console 标签里的红色报错信息', correct: true, feedback: '' },
                  { text: 'Elements 的 Styles 面板', correct: false, feedback: 'Elements/Styles 是样式不对时用的;白屏报错要看 Console。' },
                  { text: 'Network 请求列表', correct: false, feedback: 'Network 管数据/接口问题;白屏报错先看 Console 红字。' },
                ],
              },
              {
                prompt: '把问题讲清楚,哪组信息最完整?',
                options: [
                  { text: '刚才做了什么 + 现在看到什么 + 想要什么效果', correct: true, feedback: '' },
                  { text: '只发一句「为啥报错?」', correct: false, feedback: '上下文不够,AI 只能给一堆猜测。三要素:做了什么/看到什么/想要什么。' },
                  { text: '把全部代码贴上,一个字不解释', correct: false, feedback: '缺现象和预期,AI 不知道你要修什么。按时间顺序用大白话说清三件事。' },
                ],
              },
            ],
          },
          {
            symptom: '病人B:点「保存」按钮,数据没存上,页面也没提示',
            steps: [
              {
                prompt: '第一步先做什么?',
                options: [
                  { text: '描述现象 + 截图,直接问 AI', correct: true, feedback: '' },
                  { text: '重启电脑再试一次', correct: false, feedback: '慌张瞎试不解决问题。标准流程:看到问题→截图→问 AI→照做。' },
                  { text: '先打开 F12 逐行读源代码', correct: false, feedback: '原文:F12 不是第一步,是 AI 说"需要更多信息"之后的第二步。' },
                ],
              },
              {
                prompt: 'AI 要请求详情。数据/接口类问题该去哪截?',
                options: [
                  { text: 'Network 面板:重新操作一遍,截请求 URL、状态码、参数和返回', correct: true, feedback: '' },
                  { text: 'Console 面板的红字', correct: false, feedback: '数据存不上/接口出错对应 Network 面板;Console 管白屏报错。' },
                  { text: '系统任务管理器', correct: false, feedback: '那是看进程的,跟接口请求无关。去 F12 的 Network 标签。' },
                ],
              },
            ],
          },
        ],
      },
    },
  ],
}
